framework:
  rate_limiter:

    api_free:
      policy: 'sliding_window'
      limit: 100000
      interval: '24 hours'

    api_free_per_minute:
      policy: 'sliding_window'
      limit: 100
      interval: '1 minutes'

    security_throttling:
      policy: 'token_bucket'
      limit: 10
      rate: { interval: '15 minutes', amount: 5 }

    login_throttling:
        policy: 'token_bucket'
        limit: 5
        rate: { interval: '5 minutes', amount: 5 }
