framework:
  rate_limiter:

    api_free:
      policy: 'token_bucket'
      limit: 100000
      rate: { interval: '24 hours', amount: 100000 }

    api_free_per_minute:
      policy: 'token_bucket'
      limit: 100
      rate: { interval: '1 minutes', amount: 100 }

    security_throttling:
      policy: 'token_bucket'
      limit: 10
      rate: { interval: '15 minutes', amount: 5 }

    login_throttling:
        policy: 'token_bucket'
        limit: 5
        rate: { interval: '5 minutes', amount: 5 }
