# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    google:
        enabled: true
        issuer: STEXS
        digits: 6
        window: 1
        template: website/security/2fa_form.html.twig
        form_renderer: acme.custom_form_renderer
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
