<?php declare(strict_types=1);

namespace App\Security\Login;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;

class LoginFormAuthenticator extends AbstractAuthenticator
{
    public function supports(
        Request $request
    ): ?bool
    {
        // TODO: Implement supports() method.
    }

    public function onAuthenticationFailure(
        Request $request,
        AuthenticationException $exception
    ): ?Response
    {
        // TODO: Implement onAuthenticationFailure() method.
    }

    public function onAuthenticationSuccess(
        Request $request,
        TokenInterface $token,
        string $firewallName
    ): ?Response
    {
        // TODO: Implement onAuthenticationSuccess() method.
    }

    public function authenticate(
        Request $request
    ): Passport
    {
        // TODO: Implement authenticate() method.
    }

    public function createToken(
        Passport $passport,
        string $firewallName
    ): TokenInterface
    {
        return parent::createToken($passport, $firewallName); // TODO: Change the autogenerated stub
    }
}